### ISSUE TITLE
ValueError: datestring must be valid date string and not None when querying list of images of EC2

### ISSUE THREAD

**Issue by juanmarcosdev** [apache/libcloud#1700]
## Summary

It seems to be an error querying a datestring from extra data of the images of EC2

## Detailed Information

I'm newbie at using libcloud, i've already ran a file to list the images of GCP Compute Engine - not problem. Then, i tried to do the same but using AWS EC2, and i'm pretty sure that there are not problems with ACCESS_ID an SECRET_KEY, since i tried to modify these in order to damage the keys and then it appears an error with AWS AuthFailure, but when i use the correct ones, there's no problem around there. But when trying to print the list of images, i got the error ValueError: datestring must be valid date string and not None.

This includes information about your environment (which Libcloud version are
you using, which Python version, which Operating System / distribution, etc.)
and steps which are needed to reproduce it.

I'm currently using Apache Libcloud 3.6.0, Python 3.10 and Ubuntu 22.04

If you need to check out my code, you can check this repo: https://github.com/juanmarcosdev/avances-libcloud/

The file driver_gcp.py works pretty well. The one with the error is driver_aws.py

I'm using a .env file in order to keep secret my AWS credentials.

Thanks!

![Captura desde 2022-05-29 23-52-47](https://user-images.githubusercontent.com/46875325/170919501-20c8fcb5-58bd-4ba5-a596-25c777eb3855.png)

**Comment by Kami** [comment]
I tried to replicate the issue with EC2 driver, but I couldn't - it works fine for me. 

It appears that the issue is related to the response - one of the images returned doesn't seem to contain one of the extra attributes (``creation_date``) or similar.

Are you sure you are using valid key with the correct permissions for EC2? In addition to that, are you behind a proxy?

Please run your script with ``LIBCLOUD_DEBUG`` environment variable set and gist the output (https://libcloud.readthedocs.io/en/stable/troubleshooting.html#debugging - make sure you remove any secrets from the output):

```bash
LIBCLOUD_DEBUG=libcloud.log python3 driver_aws.py
```

**Comment by Kami** [comment]
Having said that^, I still think Libcloud should handle this scenario better (image doesn't contain creation date or some other date related attribute) so I will look into making a code change to handle that better.

P.S. By default ``list_images()`` may be very slow since it returns tons of data so you may want to utilize ``ex_filters`` to speed it up.

**Comment by Kami** [comment]
I believe this PR should fix this issue for you - https://github.com/apache/libcloud/pull/1701.
