### ISSUE TITLE
Website dark mode blocks top of documentation

### ISSUE THREAD

**Issue by SamuelMarks** [apache/libcloud#1876]
## Summary

![image](https://user-images.githubusercontent.com/807580/226481895-512e93de-e6ec-4766-9ebe-17b757f489b1.png)
![image](https://user-images.githubusercontent.com/807580/226481960-ff6f2aa4-150b-4d68-8b7d-c16af3d9b931.png)

## Detailed Information

Running Firefox 111.0

**Comment by Kami** [comment]
Thanks for reporting this.

I couldn't reproduce it myself - even if I resize the window it always scales nicely. What resolution are you using? What's the size of your browser window?

**Comment by SamuelMarks** [comment]
Hmm maybe it changed? - Also I'm on Firefox 116.0 (64-bit) now so maybe that fixed the issue?

**Comment by Kami** [comment]
@SamuelMarks If you can't reproduce it anymore, I will go ahead and close this ticket.

Please feel free to add a comment here or create a new ticket in case the issue appears again in the future.

**Comment by Kami** [comment]
I was able to reproduce this issue on a different laptop. I believe this change should fix it - https://github.com/apache/libcloud-site/commit/48266bff27afe5b15b5118e289560c49c4496cda.

**Comment by SamuelMarks** [comment]
Oooft; hand editing vendor code?

Also 3.3.7 of Twitter Bootstrap? - It's on 5.3.1 now. - From the copyright, that puts it at 7 years old

**Comment by Kami** [comment]
Yeah, that was the easiest thing to do. Trying to figure out how to handle it via our custom CSS definitions would likely require tons of digging and no idea if it's even possible to achieve that.

I looked into upgrading to the very least version around a year or so ago (https://libcloud.apache.org/blog/2022/03/30/website-updates.html), but it broke many things (I tried to fix it, but gave up after many hours). Before that, we ran even older versions...

At least the bootstrap CSS itself should not be vulnerable, but JavaScript part may be a different story.

And since the website is primarily static anyway (we don't accept or render any user provided input) and there are no session cookies and things like that at play, this reduces the surface area / potential impact in case there were some known security vulnerabilities.
